name: GitHub Actions to run integration tests
on: []
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: allows the use of containers from other architecture into the x86 architecture
          run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - name: run integration tests
          run: sudo make integ-tests-with-docker

